# Jekyll configuration
name: FlexibleFileSortUtility
description: The Flexible File Sort Utility is a command line application that sorts a text file alphabetically (forward or reverse).
url: https://pnnl-comp-mass-spec.github.io/FlexibleFileSortUtility/
